#management.endpoints.web.exposure.include=*
management:
  endpoints:
    web:
      exposure:
        include: "*"
  metrics:
    tags:
      application: ${spring.application.name}
#management.metrics.tags.application=${spring.application.name}
