#management.endpoints.web.exposure.include=*
management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    health:
      show-details: "always"
  metrics:
    tags:
      application: ${spring.application.name}
#management.metrics.tags.application=${spring.application.name}
#management.endpoint.health.show-details=always
